/** Canonical product data — the single source of truth for both the
  * Supabase seeder and the generated supabase/seed.sql. */

export const products = [
  // ── Bestsellers ──────────────────────────────────
  { sort_order: 1,  name: 'Double Chocolate',   slug: 'double-chocolate', flavour: 'chocolate',    category: 'cookies', price: 260, weight: '200g', is_bestseller: true, hero_color: '#5C2E0A', short_description: 'Deep cocoa, twice the crunch', long_description: 'Rich double-chocolate cookies made with pure desi ghee and a proper dose of cocoa. Intense, glossy, and the reason people call back.', tags: ['bestseller', 'chocolate', 'kids-favourite'] },
  { sort_order: 2,  name: 'Nankhatai',           slug: 'nankhatai', flavour: 'nankhatai',           category: 'cookies', price: 240, weight: '250g', is_bestseller: true, hero_color: '#C49030', short_description: 'The classic that started it all', long_description: 'Ghee-rich, cardamom-kissed nankhatai that crumbles the moment it touches your tongue. The recipe hasn\'t changed in three generations.', tags: ['bestseller', 'classic', 'ghee'] },
  { sort_order: 3,  name: 'Jam Roll Cookies',    slug: 'jam-roll-cookies', flavour: 'jam',    category: 'cookies', price: 250, weight: '250g', is_bestseller: true, hero_color: '#C2456B', short_description: 'Flaky rolls with a fruity core', long_description: 'Hand-rolled shortbread wound around a stripe of real fruit jam. Every bite is a little swirl of nostalgia.', tags: ['bestseller', 'handmade', 'fruit'] },
  { sort_order: 4,  name: 'Mix Dry Fruits',      slug: 'mix-dry-fruits', flavour: 'dryfruit',      category: 'cookies', price: 349, weight: '250g', is_bestseller: true, hero_color: '#8B4A2B', short_description: 'Loaded with cashew, almond & raisin', long_description: 'Premium cookies packed shoulder to shoulder with cashews, almonds, and raisins. This is the tin you keep for special guests.', tags: ['bestseller', 'premium', 'gifting'] },

  // ── Classic Cookies ──────────────────────────────
  { sort_order: 5,  name: 'Atta Ghee',           slug: 'atta-ghee', flavour: 'ghee',           category: 'cookies', price: 210, weight: '250g', hero_color: '#A8823F', short_description: 'Wholesome atta, pure ghee', long_description: 'Whole-wheat atta cookies with a serious ghee backbone. Rustic, satisfying, and the kind of thing you want with morning chai.', tags: ['classic', 'ghee', 'wholesome'] },
  { sort_order: 6,  name: 'Atta Namkeen',        slug: 'atta-namkeen', flavour: 'savoury',        category: 'cookies', price: 190, weight: '250g', hero_color: '#7BA05B', short_description: 'Lightly salted, savoury bite', long_description: 'Atta cookies with just enough salt and jeera. The reliable snack that pairs with everything from filter coffee to a game of cards.', tags: ['classic', 'savoury', 'jeera'] },
  { sort_order: 7,  name: 'Chocolate Brownie',   slug: 'chocolate-brownie', flavour: 'chocolate',   category: 'cookies', price: 250, weight: '200g', hero_color: '#5C2E0A', short_description: 'Fudgy brownie in cookie form', long_description: 'Dense, fudgy brownie-cookies with a soft centre and slightly crisp edge. Best served slightly warm with cold milk.', tags: ['chocolate', 'fudgy'] },
  { sort_order: 8,  name: 'Chocolate Chip',      slug: 'chocolate-chip', flavour: 'chocolate',      category: 'cookies', price: 250, weight: '250g', hero_color: '#8B4A2B', short_description: 'Golden edges, gooey middles', long_description: 'The universally loved chocolate chip. Golden brown at the edges, still soft in the middle, generous with the chips.', tags: ['classic', 'chocolate'] },
  { sort_order: 9,  name: 'Tooty Frooty',        slug: 'tooty-frooty', flavour: 'fruit',        category: 'cookies', price: 220, weight: '250g', hero_color: '#E8873A', short_description: 'Rainbow fruit bits, pure joy', long_description: 'Buttery cookies studded with candied fruit bits in every colour. The one that makes kids grin and adults nostalgic.', tags: ['nostalgic', 'kids-favourite', 'colourful'] },
  { sort_order: 10, name: 'Classic Coconut',     slug: 'classic-coconut', flavour: 'coconut',     category: 'cookies', price: 240, weight: '250g', hero_color: '#F5E6D3', short_description: 'Soft, sweet, tropical', long_description: 'Freshly grated coconut folded into a soft, mildly-sweet dough. A tropical whisper in every bite.', tags: ['classic', 'coconut'] },
  { sort_order: 11, name: 'Oreo Cookies',        slug: 'oreo-cookies', flavour: 'chocolate',        category: 'cookies', price: 240, weight: '250g', hero_color: '#2A1409', short_description: 'Chocolate wafer, cream centre', long_description: 'Dark chocolate wafers sandwiched around a smooth vanilla cream. Classic in every way.', tags: ['chocolate', 'classic'] },
  { sort_order: 12, name: 'Assorted Cookies',    slug: 'assorted-cookies', flavour: 'assorted',    category: 'cookies', price: 270, weight: '250g', hero_color: '#C49030', short_description: 'A little of everything', long_description: 'Our curated pick of the bestsellers in one tin. Ideal for when you can\'t decide, or when you\'re gifting.', tags: ['variety', 'gifting'] },

  // ── Premium Cookies ──────────────────────────────
  { sort_order: 13, name: 'Cashew Cookies',      slug: 'cashew-cookies', flavour: 'nuts',      category: 'cookies', price: 299, weight: '250g', hero_color: '#C49030', short_description: 'Butter-rich with whole cashews', long_description: 'Buttery shortbread loaded with premium whole cashews in every bite. Delicate, nutty, and a little indulgent.', tags: ['premium', 'nuts'] },
  { sort_order: 14, name: 'Almond Cookies',      slug: 'almond-cookies', flavour: 'nuts',      category: 'cookies', price: 299, weight: '250g', hero_color: '#8B661C', short_description: 'Roasted almond, deep butter', long_description: 'Roasted almonds folded into a rich, buttery dough and baked until fragrant. Pairs beautifully with kahwa.', tags: ['premium', 'nuts'] },
  { sort_order: 15, name: 'Cashew Pepper',       slug: 'cashew-pepper', flavour: 'nuts',       category: 'cookies', price: 299, weight: '250g', hero_color: '#4A8C8C', short_description: 'Sweet cashew, warm pepper kick', long_description: 'The unexpected hero — cashew cookies with cracked black pepper. Sweet, savoury, and grown-up.', tags: ['premium', 'nuts', 'unusual'] },
  { sort_order: 16, name: 'Almond Sticks',       slug: 'almond-sticks', flavour: 'nuts',       category: 'cookies', price: 250, weight: '250g', hero_color: '#A8823F', short_description: 'Crunchy sticks, generous almonds', long_description: 'Long, crunchy almond sticks with a satisfying snap. The kind of thing you dip in coffee and lose track of time.', tags: ['premium', 'nuts', 'crunchy'] },

  // ── Savoury / Snacks ─────────────────────────────
  { sort_order: 17, name: 'Garlic Toast',        slug: 'garlic-toast', flavour: 'garlic',        category: 'snacks', price: 220, weight: '1 box (~250g)', hero_color: '#C2456B', short_description: 'Crispy, garlicky, addictive', long_description: 'Twice-baked toast rubbed with roasted garlic and a whisper of butter. Impossible to stop at one.', tags: ['savoury', 'garlic'] },
  { sort_order: 18, name: 'Oregano Lavash',      slug: 'oregano-lavash', flavour: 'herb',      category: 'snacks', price: 220, weight: '1 box (~250g)', hero_color: '#7BA05B', short_description: 'Thin, herby, perfect with dips', long_description: 'Paper-thin lavash flecked with dried oregano. The one you break out with hummus, cheese, or just a cold drink.', tags: ['savoury', 'herby'] },
  { sort_order: 19, name: 'ChilliFlakes Lavash', slug: 'chilliflakes-lavash', flavour: 'spice', category: 'snacks', price: 220, weight: '1 box (~250g)', hero_color: '#E8873A', short_description: 'A slow, spreading heat', long_description: 'Lavash with generous chilli flakes baked right in. Starts subtle, ends with a warm afterglow.', tags: ['savoury', 'spicy'] },
  { sort_order: 20, name: 'Cheese Lavash',       slug: 'cheese-lavash', flavour: 'cheese',       category: 'snacks', price: 220, weight: '1 box (~250g)', hero_color: '#C49030', short_description: 'Melted cheese, crackly crisp', long_description: 'Real cheese melted into the dough, baked until crackly and golden. The evening snack that disappears fastest.', tags: ['savoury', 'cheese'] },
]
